name: yolov9
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - gitpython
  - ipython
  - opencv
  - pillow>=7.1.2
  - psutil
  - pytorch>=1.7.0
  - torchvision>=0.8.1
  - albumentations>=1.0.3
  - pycocotools>=2.0
  - pip:
      - seaborn>=0.11.0
      - thop>=0.1.1
      - tqdm>=4.64.0
      - tensorboard>=2.4.1
      - pandas>=1.1.4
      - matplotlib>=3.2.2
      - numpy>=1.18.5
      - pyyaml>=5.3.1
      - requests>=2.23.0
      - scipy>=1.4.1
